name: ragna-dev
channels:
  - conda-forge
dependencies:
  - python =3.9
  # FIXME: This is not available on Windows. We need to document this as part of the
  #  dev installation
  #  - redis-server
  - pip
  - pip:
    - redis
    - jupyter
    - python-dotenv
    - boto3
    - pytest >=6
    - mypy
    - pre-commit
    # documentation
    - mkdocs
    - mkdocs-material
    - mkdocstrings[python]
