name: ragna-dev
channels:
  - conda-forge
dependencies:
  - python =3.9
  - pip
  - git-lfs
  - pip:
      - python-dotenv
      - pytest >=6
      - pytest-mock
      - pytest-asyncio
      - pytest-playwright
      - playwright
      - mypy ==1.10.0
      - pre-commit
      - types-aiofiles
      - sqlalchemy-stubs
      - setuptools-scm
      - pip-tools
      # documentation
      - mkdocs
      - mkdocs-material
      - mkdocstrings[python]
      - mkdocs-gen-files
      - material-plausible-plugin
      - mkdocs-gallery >=0.10
      - mdx_truly_sane_lists
