name: ragna-dev
channels:
  - conda-forge
dependencies:
  - python =3.9
  - pip
  - pip:
      - python-dotenv
      - boto3
      - pytest >=6
      - pytest-mock
      - mypy ==1.6.1
      - pre-commit
      - types-aiofiles
      - sqlalchemy-stubs
      - setuptools-scm
      - pip-tools
      # documentation
      - mkdocs
      - mkdocs-material
      - mkdocstrings[python]
      - mkdocs-gen-files
      - material-plausible-plugin
      - mktestdocs
